### ISSUE TITLE
关于页面边距

### ISSUE THREAD

**Issue by sheqi** [yk-liu/yk-liu.github.io#52]
Hi，Yingkai 

我想问一下我们fork的repo，https://lifelong-robotic-vision.github.io/
页面边距是否可以调整，目前感觉我们修改的网页再pc端页面宽度比较窄。

非常感谢你的帮助！

Roger

**Comment by yk-liu** [comment]
Hi Roger

home.css 里面
.user-details{
    text-align:center;
    margin:5px auto;
    width:40%;
}
width 调成你想要的即可

Yingkai

**Comment by sheqi** [comment]
Many thanks!  success to modify it based on your suggestions
