### ISSUE TITLE
【征求意见】基于 git 的博客聚合工具

### ISSUE THREAD

**Issue by nobodxbodon** [yk-liu/yk-liu.github.io#56]
新年好，有幸从 [独立博客列表](https://github.com/timqian/chinese-independent-blogs) 发现此仓库，添加到了 [此索引](https://gitee.com/zhishi/collection-of-chinese-blogs) 。

不知可否将此博客内容作为 [针对 md 格式的博客内容聚合工具](https://gitee.com/zhishi/collection-of-chinese-blogs/blob/master/%E6%96%87%E6%A1%A3/2021-01-26-%E5%9F%BA%E4%BA%8E%20git%20%E7%9A%84%E5%8D%9A%E5%AE%A2%E8%81%9A%E5%90%88%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%88%E4%B8%80%EF%BC%89%EF%BC%9A%E8%AF%BB%E8%80%85.md) 的内容源之一？

欢迎任何意见建议。

**Comment by nobodxbodon** [comment]
你好，已有十六位博主同意将博文 git 仓库加入内容源，博文一千三百多篇。
现在搜集功能需求、做一些简单技术调研，进展 [在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)，可见统计数据、所有博文目录等。

如无不妥，之后会将此仓库也加入博客列表。谢谢。

**Comment by yk-liu** [comment]
没有问题! 感谢垂青!
